package spark.streaming.examples

import spark.streaming.{Seconds, StreamingContext}
import spark.streaming.StreamingContext._
import spark.streaming.sql.SQLRouterDStream
import spark.RDD
import spark.SparkContext._
import java.io.{File, PrintWriter}

/**
 * Counts words in UTF8 encoded, '\n' delimited text received from the network every second.
 * Usage: NetworkWordCount <master> <hostname> <port>
 *   <master> is the Spark master URL. In local mode, <master> should be 'local[n]' with n > 1.
 *   <hostname> and <port> describe the TCP server that Spark Streaming would connect to receive data.
 *
 * To run this on your local machine, you need to first run a Netcat server
 *    `$ nc -lk 9999`
 * and then run the example
 *    `$ ./run spark.streaming.examples.NetworkWordCount local[2] localhost 9999`
 */
object NetworkWordCount {
  def main(args: Array[String]) {
    if (args.length < 3) {
      System.err.println("Usage: NetworkWordCount <master> <hostname> <port>\n" +
        "In local mode, <master> should be 'local[n]' with n > 1")
      System.exit(1)
    }

    // Create the context with a 1 second batch size
    val ssc = new StreamingContext(args(0), "NetworkWordCount", Seconds(1),
      System.getenv("SPARK_HOME"), Seq(System.getenv("SPARK_EXAMPLES_JAR")))

    // Create a NetworkInputDStream on target ip:port and count the
    // words in input stream of \n delimited test (eg. generated by 'nc') 
    val x = ssc.socketTextStream(args(1), 9999).map(l => {val ll = l.split(","); (ll(0),ll(1))})
    val y = ssc.socketTextStream(args(1), 9998).map(l => {val ll = l.split(","); (ll(0),ll(1))})
    val z = ssc.socketTextStream(args(1), 9997).map(l => {val ll = l.split(","); (ll(0),ll(1))})

    val joined = x.join(y).join(z)
    joined.print()




    //    val wordCounts = words.window(Seconds(10),Seconds(1)).map(x => (x, 1)).reduceByKey(_ + _)
//    val words2 = lines.flatMap(_.split(" ")).filter(_.contains("b"))
//    val wordCounts2 = words2.window(Seconds(10),Seconds(1)).map(x => (x, 2)).reduceByKey(_ + _)
    //wordCounts.print()
    //wordCounts2.print()
//    val jj = wordCounts.cogroup(wordCounts2)
//    jj.print()




    ssc.start()
  }
}
